env:
  name: dev

#view:
#  site:
#    needLoginArticleReadCount: 30 # 需要登录才能阅读的文章阅读次数
#    zsxqArticleReadCount: 20 # 知识星球用户才能阅读的文章阅读次数统计间隔，单位：分钟
#    websiteName: 澎湃博客
#    websiteLogoUrl: https://paicoding.com/img/icon.png
#    websiteFaviconIconUrl: https://paicoding.com/img/icon.png
#    zsxqUrl: https://paicoding.com/article/detail/314
#    zsxqPosterUrl: https://cdn.tobebetterjavaer.com/tobebetterjavaer/images/javabetter.jpg
#    contactMeTitle: 联系我 - 沉默王二的狗腿子
#    contactMeWxQrCode: https://cdn.tobebetterjavaer.com/paicoding/paicoding-qrcode.png
#    contactMeStarQrCode: https://cdn.tobebetterjavaer.com/tobebetterjavaer/images/qiye-weixin.png
#    pageSize: 20
#    cdnImgStyle: null
#    websiteRecord: 欢迎大帅哥登场！
#    wxLoginUrl: http://weixin.qq.com/r/WxwpMefE-rqBraNS90lJ
#    host: http://127.0.0.1:${server.port}
#    welcomeInfo: 欢迎来到澎湃博客，戳<a href="www.baidu.com">澎湃博客全方位视角解读</a>了解我们
#    oss: null

hpl:
  jwt:
    issuer: hpl-blog    # 签发者
    secret: hyper       # 签名密钥
    expire: 259200000   # 默认过期时间，3天

