view:
  site:
    needLoginArticleReadCount: 30 # 需要登录才能阅读的文章阅读次数
    zsxqArticleReadCount: 20 # 知识星球用户才能阅读的文章阅读次数统计间隔，单位：分钟
    websiteName: 澎湃博客
    websiteLogoUrl: https://paicoding.com/img/icon.png
    websiteFaviconIconUrl: https://paicoding.com/img/icon.png
    zsxqUrl: https://paicoding.com/article/detail/314
    zsxqPosterUrl: https://cdn.tobebetterjavaer.com/tobebetterjavaer/images/javabetter.jpg
    contactMeTitle: 联系我 - 沉默王二的狗腿子
    contactMeWxQrCode: https://cdn.tobebetterjavaer.com/paicoding/paicoding-qrcode.png
    contactMeStarQrCode: https://cdn.tobebetterjavaer.com/tobebetterjavaer/images/qiye-weixin.png
    pageSize: 20
    cdnImgStyle: null
    websiteRecord: 欢迎大帅哥登场！
    wxLoginUrl: http://weixin.qq.com/r/WxwpMefE-rqBraNS90lJ
    host: http://127.0.0.1:${server.port}
    welcomeInfo: 欢迎来到澎湃博客，戳<a href="www.baidu.com">澎湃博客全方位视角解读</a>了解我们
    oss: null

server:
  port: 8181

spring:
  config:
    import: application-config.yml


  data:
    redis:
      host: 192.168.88.128
      port: 6379
      database: 0

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.88.128:3306/hpl_blog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 1234

  thymeleaf:
    prefix: classpath:/templates/   # 页面模板位置
    suffix: .html                   # 页面模板后缀名
    mode: HTML
    encoding: UTF-8
#    servlet:
#      content-type: text/html
    cache: false                     # 开发时设置为false，生产时设置为true


mybatis-plus:
  global-config:
    banner: false                       # 关闭mp的banner打印
  configuration:
    map-underscore-to-camel-case: true  # 开启下滑线转驼峰
  mapper-locations: classpath*:com/hpl/**/mapping/*.xml